### ISSUE TITLE
Presença

### ISSUE THREAD

**Issue by fsantanna** [gbarros/Reativos#1]
Você não assinou a lista de presença de ontem, 22/03, certo?

**Comment by gbarros** [comment]
Sim! Eu cheguei um pouco tarde e já tinha passado da minha mesa...
Esqueci de buscar para assinar.

Obrigado por lembrar!

Att,(gbbabarros@gmail.com)

2016-03-23 7:12 GMT-03:00 fsantanna notifications@github.com:

**Comment by fsantanna** [comment]
ok
